<?php
/**
 * Generated by Haxe 4.1.1
 */

namespace shoppingcart;

use \php\Boot;

class CartModel {
	/**
	 * @var string
	 */
	public $id;
	/**
	 * @var string
	 */
	public $storeId;

	/**
	 * @return void
	 */
	public function __construct () {
	}
}

Boot::registerClass(CartModel::class, 'shoppingcart.CartModel');
