<?php
/**
 * Generated by Haxe 4.1.1
 */

namespace shoppingcart;

use \php\Boot;

class ItemModel {
	/**
	 * @var string
	 */
	public $cartId;
	/**
	 * @var int
	 */
	public $idx;
	/**
	 * @var string
	 */
	public $itemId;
	/**
	 * @var float
	 */
	public $price;
	/**
	 * @var int
	 */
	public $qty;

	/**
	 * @return void
	 */
	public function __construct () {
	}
}

Boot::registerClass(ItemModel::class, 'shoppingcart.ItemModel');
